--TABLOLARA VERİLERİ EKLEME
insert into users (username, email, creation_date, is_active) values ('cyoodall0', 'gkira0@yale.edu', '2012-04-27 06:13:42', true);
insert into users (username, email, creation_date, is_active) values ('osybbe1', 'efreiburger1@altervista.org', '2012-05-02 12:43:15', false);
insert into users (username, email, creation_date, is_active) values ('chaskett2', 'mbarriball2@instagram.com', '2011-03-20 21:55:40', true);
insert into users (username, email, creation_date, is_active) values ('treeves3', 'dscottrell3@livejournal.com', '2012-04-18 16:52:43', true);
insert into users (username, email, creation_date, is_active) values ('ugouch4', 'rspinas4@com.com', '2009-08-15 13:52:21', false);
insert into users (username, email, creation_date, is_active) values ('khof5', 'ndyball5@usa.gov', '2010-12-04 23:53:27', true);
insert into users (username, email, creation_date, is_active) values ('lhaslock6', 'fbaudry6@ning.com', '2012-06-03 16:56:56', true);
insert into users (username, email, creation_date, is_active) values ('lbalducci7', 'apostgate7@stumbleupon.com', '2011-03-25 02:16:20', true);
insert into users (username, email, creation_date, is_active) values ('scamilletti8', 'cbatson8@bbb.org', '2012-06-16 16:43:47', true);
insert into users (username, email, creation_date, is_active) values ('dtilliard9', 'smarin9@rakuten.co.jp', '2011-04-23 10:23:15', true);
insert into users (username, email, creation_date, is_active) values ('kbrocktona', 'acusteda@forbes.com', '2012-01-31 03:22:53', false);
insert into users (username, email, creation_date, is_active) values ('ocustanceb', 'rmaccurleyb@nsw.gov.au', '2011-08-24 02:04:41', true);
insert into users (username, email, creation_date, is_active) values ('rlavenc', 'balgeoc@a8.net', '2009-08-01 23:44:44', true);
insert into users (username, email, creation_date, is_active) values ('dlamzedd', 'bwitherupd@ox.ac.uk', '2011-02-13 09:57:17', true);
insert into users (username, email, creation_date, is_active) values ('mmarusyake', 'dlarensone@usda.gov', '2012-03-27 03:27:03', true);
insert into users (username, email, creation_date, is_active) values ('dhorwellf', 'ewoolcocksf@cargocollective.com', '2009-08-01 16:48:57', true);
insert into users (username, email, creation_date, is_active) values ('icouthg', 'nkolyaging@unesco.org', '2010-06-07 03:34:37', false);
insert into users (username, email, creation_date, is_active) values ('igroomeh', 'tbargeryh@uiuc.edu', '2010-12-03 20:28:28', true);
insert into users (username, email, creation_date, is_active) values ('gwilfingi', 'rpetkensi@reverbnation.com', '2011-04-16 07:17:46', true);
insert into users (username, email, creation_date, is_active) values ('sgleavesj', 'craccioj@ted.com', '2011-03-20 09:58:32', true);

insert into categories(name, creation_date) values('music','2008-07-24 16:27:48');
insert into categories(name, creation_date) values('sports','2008-07-25 13:21:12');
insert into categories(name, creation_date) values('gaming','2008-07-25 18:10:23');
insert into categories(name, creation_date) values('finance','2008-10-26 08:56:38');

INSERT INTO posts (user_id, category_id, title, content, view_count, creation_date, is_published)
VALUES
    (1, 1, 'Favorite Music Album', 'I recently discovered an amazing music album that I can''t stop listening to. It''s a must-hear for all music enthusiasts!', 25000, TIMESTAMP '2016-05-10 14:30:00', true),
    (2, 1, 'Concert Experience', 'Last night, I attended a mesmerizing concert. The artist performed their best hits and the atmosphere was electric!', 125000, TIMESTAMP '2015-09-20 19:45:00', false),
    (3, 1, 'New Song Release', 'Check out this latest song release by a talented artist. The lyrics and melody are so captivating.', 50000, TIMESTAMP '2017-03-02 10:15:00', true),
    (4, 2, 'Game Highlights', 'Yesterday''s game was filled with incredible moments. Here are the top highlights that left fans in awe!', 75000, TIMESTAMP '2016-08-15 21:10:00', true),
    (5, 2, 'Upcoming Tournament', 'Attention all sports fans! Get ready for an exciting tournament featuring the best athletes from around the world.', 100000, TIMESTAMP '2015-11-05 13:20:00', true),
    (6, 2, 'Player Spotlight', 'In this article, we shine a spotlight on an exceptional athlete who has been dominating their sport.', 30000, TIMESTAMP '2018-01-18 08:40:00', true),
    (7, 3, 'Game Review', 'I recently played an immersive video game that kept me hooked for hours. Here''s my in-depth review and rating.', 150000, TIMESTAMP '2013-02-28 16:55:00', true),
    (8, 3, 'Easter Eggs', 'Discover hidden easter eggs in this popular video game. These secrets will blow your mind!', 40000, TIMESTAMP '2018-10-12 11:25:00', true),
    (9, 3, 'Multiplayer Madness', 'Grab your friends and prepare for an epic gaming session. This multiplayer game is an absolute blast!', 80000, TIMESTAMP '2019-05-05 17:30:00', false),
    (10, 4, 'Investment Tips', 'Are you looking to invest your money wisely? Here are some valuable tips for making sound financial investments.', 500000, TIMESTAMP '2015-06-25 09:15:00', true),
    (11, 4, 'Budgeting 101', 'Learn the basics of budgeting and how it can help you achieve your financial goals and live a stress-free life.', 1000000, TIMESTAMP '2014-12-09 12:45:00', false),
    (12, 4, 'Retirement Planning', 'It''s never too early to start planning for retirement. Discover essential strategies to secure your financial future.', 200000, TIMESTAMP '2014-04-14 15:50:00', true),
    (13, 1, 'Best Music Collaborations', 'We''ve compiled a list of the most iconic music collaborations that have taken the industry by storm.', 60000, TIMESTAMP '2019-07-19 18:05:00', true),
    (14, 1, 'Song Recommendation', 'Looking for new music? Check out this incredible song that has been making waves in the music scene.', 90000, TIMESTAMP '2019-10-30 10:35:00', true),
    (15, 1, 'Music Festival Announcement', 'Mark your calendars for the upcoming music festival, featuring a star-studded lineup of artists!', 35000, TIMESTAMP '2016-02-12 14:00:00', true),
    (16, 2, 'Athlete Interview', 'We sat down with a renowned athlete to discuss their journey, challenges, and secrets to success.', 20000, TIMESTAMP '2016-03-17 16:20:00', true),
    (17, 2, 'Team Rivalry', 'The rivalry between these two teams is heating up. Stay updated with the latest news and match results.', 70000, TIMESTAMP '2015-11-25 20:55:00', true),
    (18, 2, 'Sportsmanship and Fair Play', 'In this article, we reflect on the importance of sportsmanship and fair play in competitive sports.', 40000, TIMESTAMP '2015-05-01 12:00:00', true),
    (19, 3, 'Game Development Insights', 'Get an exclusive behind-the-scenes look at the game development process of an upcoming blockbuster title.', 120000, TIMESTAMP '2014-04-08 14:50:00', false),
    (20, 3, 'Gaming Tips and Tricks', 'Unlock secret achievements and level up your gaming skills with these valuable tips and tricks.', 45000, TIMESTAMP '2017-09-15 09:10:00', true),
    (1, 3, 'Game Release Announcement', 'We''re thrilled to announce the release of an exciting new game that will revolutionize the gaming industry.', 60000, TIMESTAMP '2017-03-28 11:30:00', true),
    (2, 4, 'Cryptocurrency Guide', 'Discover the world of cryptocurrencies and learn how to navigate this rapidly evolving digital landscape.', 300000, TIMESTAMP '2019-01-05 08:20:00', true),
    (3, 4, 'Debt Management Strategies', 'Struggling with debt? Explore effective strategies to manage your debts and regain financial freedom.', 800000, TIMESTAMP '2017-10-19 13:40:00', true),
    (4, 4, 'Savings Techniques', 'Learn practical ways to save money and build a strong financial foundation for a secure future.', 150000, TIMESTAMP '2018-05-20 16:15:00', true),
	(12, 1, 'Song of the Week', 'Discover the trending song of the week that has been dominating music charts worldwide.', 80000, TIMESTAMP '2013-09-05 09:30:00', true),
	(13, 1, 'Concert Announcement', 'Exciting news! A renowned artist will be performing live in your city soon. Get your tickets now!', 40000, TIMESTAMP '2016-10-18 17:15:00', true),
	(15, 2, 'Player Transfer Rumors', 'Rumors are swirling about potential player transfers in the upcoming season. Stay updated with the latest speculation.', 60000, TIMESTAMP '2016-11-29 11:40:00', false),
	(16, 2, 'Athlete Profile: Rising Star', 'We profile a young and talented athlete who is making waves in their sport. Learn about their journey to success.', 35000, TIMESTAMP '2015-01-12 14:55:00', true),
	(8, 3, 'Game of the Year', 'Discover the highly anticipated game that has been crowned "Game of the Year" by critics and players alike.', 90000, TIMESTAMP '2019-02-25 10:20:00', true),
	(9, 3, 'Exclusive Gameplay Footage', 'Get a sneak peek at the exclusive gameplay footage of an upcoming game that will blow your mind.', 50000, TIMESTAMP '2017-04-08 19:30:00', false),
	(11, 4, 'Real Estate Investment Guide', 'Thinking about investing in real estate? This comprehensive guide covers everything you need to know.', 700000, TIMESTAMP '2014-05-21 16:40:00', true),
	(12, 4, 'Tax Saving Tips', 'Maximize your tax savings with these expert tips and strategies for individuals and small businesses.', 250000, TIMESTAMP '2016-06-10 12:55:00', true),
	(13, 1, 'Behind the Scenes: Music Video', 'Go behind the scenes of the latest music video release and discover the creative process involved.', 40000, TIMESTAMP '2019-08-15 10:25:00', false),
	(14, 1, 'Song Lyrics Analysis', 'Delve into the lyrics of a popular song and uncover its hidden meanings and powerful messages.', 75000, TIMESTAMP '2019-01-02 13:40:00', true),
	(5, 2, 'Greatest Sporting Moments', 'Relive the greatest sporting moments that have left a lasting impact on fans and athletes alike.', 55000, TIMESTAMP '2019-10-30 16:55:00', false),
	(16, 2, 'Fitness Tips for Beginners', 'Embarking on a fitness journey? Learn valuable tips for beginners to kickstart a healthy lifestyle.', 30000, TIMESTAMP '2015-02-12 19:10:00', true),
	(17, 3, 'Game Soundtrack Release', 'The captivating soundtrack of a popular game is now available. Immerse yourself in its stunning music.', 65000, TIMESTAMP '2017-11-05 14:25:00', true),
	(18, 3, 'Game Streaming Marathon', 'Join us for an exciting game streaming marathon, featuring some of the most popular streamers.', 90000, TIMESTAMP '2018-03-19 17:40:00', true),
	(19, 4, 'Investment Opportunities', 'Explore promising investment opportunities in emerging markets that have the potential for high returns.', 450000, TIMESTAMP '2019-09-15 20:55:00', true),
	(20, 4, 'Financial Planning for Families', 'Learn effective financial planning strategies for families to achieve long-term financial security.', 150000, TIMESTAMP '2013-04-28 11:10:00', true),
	(17, 1, 'Upcoming Music Collaboration', 'Exciting news! Two renowned artists are teaming up for a highly anticipated music collaboration.', 85000, TIMESTAMP '2016-07-05 12:30:00', true),
	(20, 1, 'Music Festival Recap', 'Relive the incredible moments from the recent music festival, including performances and special guest appearances.', 55000, TIMESTAMP '2016-08-18 18:15:00', false),
	(3, 2, 'Athlete Spotlight', 'We shine a spotlight on an exceptional athlete, highlighting their achievements, dedication, and impact on their sport.', 40000, TIMESTAMP '2018-09-30 11:40:00', true),
	(4, 2, 'Sports Trivia Challenge', 'Test your sports knowledge with our ultimate trivia challenge. Are you ready to prove your expertise?', 65000, TIMESTAMP '2015-01-13 14:55:00', true),
	(9, 3, 'Game Developer Interview', 'We sit down with a game developer to discuss the creative process, challenges, and insights into their latest game.', 75000, TIMESTAMP '2014-02-26 10:20:00', false),
	(6, 3, 'Game Rumors and Speculations', 'Get the latest scoop on upcoming games with our roundup of rumors and speculations from the gaming industry.', 48000, TIMESTAMP '2018-04-10 19:30:00', true),
	(7, 4, 'Investment Portfolio Diversification', 'Learn the importance of diversifying your investment portfolio and strategies to achieve a balanced approach.', 560000, TIMESTAMP '2013-05-23 16:40:00', true),
	(18, 4, 'Personal Finance Tips for Young Professionals', 'Essential personal finance tips to help young professionals establish a strong financial foundation.', 280000, TIMESTAMP '2018-06-12 12:55:00', true),
	(9, 1, 'Music Playlist for Relaxation', 'Discover a carefully curated music playlist that will help you unwind and relax after a long day.', 42000, TIMESTAMP '2018-08-25 10:25:00', true),
	(10, 1, 'Music Genre Exploration', 'Explore a lesser-known music genre that deserves recognition for its unique sound and cultural significance.', 78000, TIMESTAMP '2017-01-12 13:40:00', true),
	(11, 2, 'Sports Documentary Recommendation', 'Immerse yourself in the world of sports with this compelling and thought-provoking documentary recommendation.', 52000, TIMESTAMP '2017-11-03 16:55:00', true),
	(12, 2, 'Sports Training Tips', 'Gain valuable insights into effective sports training techniques to enhance performance and prevent injuries.', 38000, TIMESTAMP '2015-02-15 19:10:00', false),
	(13, 3, 'Game Cosplay Showcase', 'Witness the extraordinary craftsmanship of talented cosplayers as they bring game characters to life.', 62000, TIMESTAMP '2018-11-15 14:25:00', false),
	(4, 3, 'Game Speedrun World Record', 'A speedrunner has set a new world record in a popular game. Explore their incredible speedrunning techniques.', 94000, TIMESTAMP '2019-03-23 17:40:00', true),
	(5, 4, 'Retirement Planning Guide', 'Plan for a comfortable and secure retirement with our comprehensive guide covering savings, investments, and more.', 510000, TIMESTAMP '2015-09-23 20:55:00', true),
	(19, 4, 'Financial Wellness for Small Business Owners', 'Discover practical strategies to achieve financial wellness and success as a small business owner.', 190000, TIMESTAMP '2016-05-02 11:10:00', true),
	(8,3,'Gaming Equipments', 'In the world of gaming, having the right equipment can significantly enhance your gaming experience.', 73000, TIMESTAMP '2017-11-15 14:26:00', true);

insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (41, 8, 'Music is the universal language that speaks to our souls.', '2022-01-24 15:57:38', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (15, 19, 'This blog post perfectly captures the magic of music.', '2021-10-24 13:19:15', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (25, 11, 'I am constantly amazed by the power of music to evoke emotions.', '2021-06-07 20:05:57', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, 12, 'The way music can transport us to different times and places is incredible.', '2021-03-12 20:21:22', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (42, 3, 'I couldnt agree more with the points made in this blog post. Music is life!', '2022-08-24 19:15:58', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (34, 9, 'Music has the ability to heal and bring people together.', '2023-04-14 01:35:09', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (41, null, 'The passion and dedication that musicians pour into their craft is inspiring.', '2021-11-17 00:59:32', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 14, 'I have discovered so many amazing artists and songs through this blog.', '2021-08-05 22:07:48', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 14, 'Music has the power to uplift our spirits and brighten even the darkest days.', '2022-09-27 12:55:43', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (15, 19, 'I am grateful for the role music plays in my life. It is a constant companion.', '2023-04-26 04:22:38', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (34, 4, 'The way music can capture and express complex emotions is truly remarkable.', '2020-07-16 16:38:28', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (15, null, 'This blog post reminds me of the incredible diversity of music genres and styles.', '2022-10-10 22:32:08', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (26, null, 'Music has the power to ignite memories and take us back in time.', '2021-05-07 17:40:51', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 16, 'I love how this blog post highlights the importance of music education.', '2023-06-10 02:39:04', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (25, 10, 'Music is a form of self-expression that allows us to share our innermost thoughts and feelings.', '2020-10-13 22:40:35', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, null, 'The impact of music on our mental and emotional well-being is profound.', '2023-02-04 13:48:09', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (49, 7, 'This blog post perfectly articulates the influence of music on culture and society.', '2022-10-24 05:17:05', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (3, 14, 'I am constantly in awe of the talent and creativity of musicians.', '2022-08-23 10:15:59', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (2, null, 'Music has the ability to bring joy and comfort to people from all walks of life.', '2023-01-21 15:16:56', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, 6, 'I resonate with the idea that music is a soundtrack to our lives.', '2021-12-20 04:19:51', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (25, null, 'This blog post is a beautiful tribute to the transformative power of music.', '2021-10-30 11:13:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (3, 14, 'Music has the power to inspire, motivate, and empower us.', '2020-11-08 11:00:33', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (14, 8, 'I cant imagine a world without music. It adds color and depth to our existence.', '2021-11-07 01:43:08', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 4, 'I appreciate how this blog post explores the connection between music and memories.', '2020-10-17 03:54:54', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (42, 2, 'Music has the ability to spark a range of emotions, from happiness to nostalgia.', '2021-12-24 08:08:42', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (26, 2, 'I am grateful for the artists who use their music to address social issues and promote change.', '2023-03-02 00:12:58', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (25, 10, 'This blog post highlights the role of music in celebrating cultural diversity.', '2021-04-25 22:27:11', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (14, 17, 'I love how music can create a sense of unity and bring people together.', '2020-08-09 20:37:47', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (2, 13, 'Music has the power to transcend language barriers and communicate on a deeper level.', '2022-05-01 16:17:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (14, 16, 'This blog post perfectly captures the thrill of discovering new music.', '2023-03-27 21:22:14', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 8, 'I am amazed by the way music can resonate with different individuals in unique ways.', '2022-12-20 20:29:29', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (13, 15, 'Music is a constant companion in both the highs and lows of life.', '2022-02-24 09:19:06', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (42, 17, 'I am inspired by the stories of musicians who overcome challenges to pursue their passion.', '2022-09-29 01:05:09', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (2, 15, 'This blog post reminds me of the incredible influence that music has on our emotions.', '2023-05-06 05:12:12', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (13, 6, 'I am grateful for the artists who use their music to bring awareness to important causes.', '2022-10-27 21:28:25', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (26, 19, 'Music has the ability to evoke memories and transport us to specific moments in time.', '2020-08-03 04:12:57', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (13, 3, 'This blog post highlights the power of music to bring comfort and solace during difficult times.', '2022-07-31 08:05:11', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, 18, 'I am constantly amazed by the creativity and innovation within the music industry.', '2023-05-15 01:57:08', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (14, 18, 'Music is a form of self-expression that allows us to communicate without words.', '2021-02-01 03:42:01', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 19, 'This blog post perfectly captures the way music can give voice to our deepest emotions.', '2022-02-27 10:05:53', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, 13, 'I love how music has the ability to bring back memories and stir nostalgia.', '2020-06-20 08:37:54', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (34, 16, 'Music has the power to provide a sense of escapism and transport us to different worlds.', '2020-11-05 21:46:18', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (49, 2, 'This blog post reminds me of the joy and excitement that music concerts bring.', '2022-06-01 04:03:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (2, null, 'I am grateful for the artists who use their platform to spread positivity and inspire others.', '2022-08-10 02:11:14', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, null, 'Music is a source of inspiration and a catalyst for creativity in my own life.', '2023-02-22 04:17:19', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 19, 'This blog post perfectly articulates the influence of music on personal growth and self-discovery.', '2021-10-18 03:08:17', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (34, 2, 'I appreciate the way music can evoke a wide range of emotions and create a deep connection.', '2022-06-25 10:13:51', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (14, 1, 'Music has the ability to unite people from different backgrounds and cultures.', '2023-01-20 23:55:00', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (13, 9, 'This blog post highlights the therapeutic benefits of music for our mental well-being.', '2020-06-22 01:21:07', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (49, null, 'I am constantly in awe of the way music can evoke memories and emotions with just a few notes.', '2021-02-12 13:21:34', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, 9, 'Music has the power to make us feel understood, even when we cant find the right words.', '2023-05-26 14:34:28', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (33, 13, 'This blog post reminds me of the incredible artistry and skill that goes into creating music.', '2020-11-01 00:39:46', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (41, 11, 'I am grateful for the artists who use their music to inspire change and spark conversations.', '2021-01-17 18:13:15', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (13, 7, 'Music is a form of self-care that allows us to escape from the stresses of everyday life.', '2023-02-01 13:16:59', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (2, 12, 'This blog post perfectly captures the way music can create a sense of belonging and community.', '2022-02-04 01:25:29', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (49, 8, 'I appreciate the way music can provide a sense of comfort and solace during challenging times.', '2023-05-30 14:46:33', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (42, 7, 'Music has the ability to bring people together and foster a sense of unity and understanding.', '2022-04-14 18:20:04', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (42, 20, 'This blog post highlights the way music can evoke nostalgia and transport us to specific moments.', '2022-09-06 17:07:57', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (3, 6, 'I am constantly amazed by the way music can tap into our emotions and touch our souls.', '2021-10-28 09:55:13', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, 5, 'Music is a universal language that has the power to bridge cultural and language barriers.', '2022-12-27 03:11:12', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, 15, 'This blog post reminds me of the way music can serve as a form of self-expression and catharsis.', '2020-06-19 16:33:38', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (14, 16, 'I am grateful for the artists who use their music to tell powerful stories and shed light on important issues.', '2021-04-30 11:25:28', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (34, 8, 'Music has the ability to inspire and motivate us to overcome challenges and reach for our dreams.', '2022-10-05 09:20:48', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (3, 20, 'This blog post perfectly captures the way music can bring joy and happiness into our lives.', '2022-04-19 17:16:02', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (33, 19, 'I appreciate the way music can serve as a soundtrack to our lives, marking significant moments and experiences.', '2020-09-20 08:13:37', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (1, 18, 'Music has the power to evoke memories and emotions in a way that words alone cannot.', '2023-05-10 20:21:49', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (49, 16, 'This blog post highlights the way music can foster a sense of connection and empathy among listeners.', '2022-08-26 16:07:27', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (34, 16, 'I am constantly in awe of the way music can transport us to different times and places with just a few notes.', '2022-09-05 12:02:03', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (13, null, 'Music is a powerful tool for self-expression and allows us to communicate our innermost thoughts and feelings.', '2021-11-25 21:14:32', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (50, null, 'This blog post reminds me of the way music has the ability to inspire and uplift us, even in the darkest times.', '2022-10-23 12:12:01', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (6, 2, 'Sports bring people together like nothing else. It is a beautiful thing.', '2021-07-27 06:23:53', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (35, 1, 'I am constantly in awe of the dedication and athleticism of these athletes.', '2021-07-07 18:54:54', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (6, null, 'This blog post perfectly captures the thrill and excitement of sports.', '2022-06-10 09:44:37', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 13, 'Sports have a way of inspiring us and pushing us beyond our limits.', '2022-06-17 07:22:34', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (4, 15, 'I couldnt agree more with the points made in this blog post. Sports truly unite us.', '2021-04-15 04:16:25', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (5, 13, 'I love how sports can teach us valuable life lessons about teamwork and perseverance.', '2022-09-02 17:55:23', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (43, null, 'The way athletes overcome obstacles and achieve greatness is truly inspiring.', '2021-09-08 19:10:51', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (52, 10, 'I have discovered so many incredible sports moments and stories through this blog.', '2021-02-11 20:45:22', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (51, 1, 'Sports have the power to uplift our spirits and ignite our passion.', '2022-11-07 19:53:37', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 2, 'I am grateful for the role sports play in bringing communities together.', '2020-08-26 15:01:53', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (17, null, 'The intensity and competitiveness of sports is captivating.', '2021-11-03 09:56:48', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (5, 15, 'This blog post highlights the impact that sports can have on personal growth and character development.', '2022-04-02 18:32:09', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (52, 13, 'Sports have a way of creating memories that last a lifetime.', '2023-05-19 10:57:54', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (16, null, 'I appreciate the way sports can teach us about grace, sportsmanship, and respect.', '2022-05-03 06:11:09', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 16, 'Sports are a celebration of the human spirit and what we can achieve with determination.', '2022-02-19 03:28:49', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (36, 13, 'The way sports can captivate and engage millions of fans is incredible.', '2021-10-13 05:54:32', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (4, 6, 'This blog post reminds me of the incredible stories of triumph and resilience in sports.', '2023-02-16 04:17:08', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (27, 13, 'I am constantly in awe of the skill and athleticism of these athletes.', '2022-09-17 13:41:22', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (5, 6, 'Sports have the ability to transcend cultural boundaries and bring people together from all walks of life.', '2021-07-27 07:04:57', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (35, 10, 'I resonate with the idea that sports are a universal language that everyone can understand.', '2023-01-19 07:50:36', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (16, 11, 'This blog post is a testament to the power of sports in inspiring future generations.', '2022-03-07 11:18:25', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (4, 10, 'Sports have a way of pushing us beyond our comfort zones and unlocking our full potential.', '2022-02-22 03:40:32', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (17, 10, 'I cant imagine a world without sports. They add excitement and joy to our lives.', '2023-03-31 12:28:01', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (43, 20, 'I appreciate how this blog post explores the impact of sports on physical and mental well-being.', '2021-01-28 23:01:38', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (5, null, 'Sports have the power to teach us about discipline, commitment, and hard work.', '2020-11-21 15:09:29', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (6, 16, 'This blog post perfectly captures the way sports can create lifelong friendships and camaraderie.', '2020-07-24 04:59:22', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (5, 16, 'I am grateful for the athletes who use their platform to make a positive impact on society.', '2023-03-22 14:10:08', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (16, 9, 'Sports have a way of teaching us about resilience and bouncing back from setbacks.', '2022-03-26 14:47:53', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (43, 1, 'This blog post highlights the way sports can inspire us to chase our dreams and never give up.', '2020-08-06 22:35:03', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (16, 19, 'I am constantly amazed by the passion and dedication of sports fans around the world.', '2022-02-24 12:07:58', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (44, 1, 'Sports have the ability to break down barriers and unite people from different cultures and backgrounds.', '2022-05-15 21:46:33', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (4, 11, 'This blog post reminds me of the incredible sportsmanship and fair play that exists in the world of sports.', '2021-02-09 02:52:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (36, 20, 'I am grateful for the moments of joy and excitement that sports bring into our lives.', '2020-10-06 20:00:59', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 11, 'Sports have the power to instill values such as teamwork, discipline, and perseverance.', '2021-01-22 06:27:59', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (16, 9, 'This blog post perfectly captures the way sports can ignite a sense of community and belonging.', '2022-12-22 04:14:59', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (16, 7, 'I appreciate the way sports can teach us about the importance of setting goals and working hard to achieve them.', '2021-11-13 17:39:37', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (35, 12, 'Sports have a way of capturing our hearts and making us feel a part of something bigger.', '2021-02-28 03:27:10', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (18, 18, 'This blog post highlights the way sports can provide a sense of escape and entertainment in our busy lives.', '2023-01-07 13:59:55', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 2, 'I am constantly in awe of the dedication and sacrifices that athletes make to excel in their sport.', '2021-10-17 10:48:16', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (52, 6, 'Sports have the ability to inspire us to push our limits and reach for greatness.', '2023-04-25 06:24:01', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (44, 8, 'This blog post reminds me of the unforgettable sports moments that have shaped history.', '2021-03-27 04:06:21', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (36, 5, 'I am grateful for the athletes who serve as role models for future generations.', '2020-07-10 21:16:41', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (27, 17, 'Sports have a way of teaching us about resilience and never giving up, both on and off the field.', '2022-08-15 07:03:39', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (35, 3, 'This blog post perfectly captures the way sports can teach us about the importance of teamwork and cooperation.', '2023-06-08 07:57:44', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 5, 'I appreciate the way sports can bring people from different backgrounds together, fostering understanding and respect.', '2021-12-16 15:47:47', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (51, 7, 'Sports have the power to transform lives and inspire positive change in communities.', '2023-05-20 02:45:24', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (35, 9, 'This blog post highlights the way sports can fuel our competitive spirit and drive us to excel.', '2020-09-23 20:17:34', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (6, 20, 'I am constantly amazed by the sheer athleticism and skill displayed by athletes in various sports.', '2022-07-17 23:19:05', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (44, 16, 'Sports have the ability to create lasting memories that we can cherish for a lifetime.', '2022-03-04 04:09:58', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (27, 2, 'This blog post reminds me of the excitement and anticipation that comes with watching a thrilling sports event.', '2023-04-17 16:59:44', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 14, 'I am grateful for the moments of pure joy and celebration that sports bring into our lives.', '2022-09-29 19:16:56', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 17, 'Sports have a way of uniting people, regardless of their differences, through a shared love for the game.', '2020-09-13 22:44:25', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (4, null, 'This blog post highlights the way sports can teach us important lessons about resilience and perseverance in the face of challenges.', '2022-10-29 03:12:02', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (4, 14, 'I appreciate the way sports can bring out the best in people and inspire acts of kindness and sportsmanship.', '2023-04-19 04:39:48', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (17, 8, 'Sports have the power to create unforgettable stories of triumph, courage, and determination.', '2022-12-09 01:31:17', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (43, 7, 'This blog post perfectly captures the electrifying atmosphere of a live sports event.', '2020-11-01 03:05:22', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (36, 11, 'I am constantly in awe of the dedication and sacrifices athletes make to reach the pinnacle of their sport.', '2023-03-17 22:17:57', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (51, 16, 'Sports have the ability to transcend age, gender, and background, creating a sense of unity among fans.', '2022-09-12 12:21:12', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (17, 7, 'This blog post reminds me of the incredible camaraderie and bonds formed through participation in team sports.', '2022-01-27 17:10:14', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (43, 3, 'I am grateful for the values instilled by sports, such as hard work, perseverance, and sportsmanship.', '2020-08-11 04:08:48', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (51, 15, 'Sports have a way of pushing us to our limits and revealing our true potential.', '2021-08-06 00:15:58', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (52, 12, 'This blog post highlights the way sports can inspire us to overcome obstacles and achieve our goals.', '2022-12-03 06:55:30', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (17, null, 'I appreciate the way sports can teach us about the importance of fair play and respect for opponents.', '2022-12-01 20:24:58', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (6, 18, 'Sports have the power to ignite passion and create lifelong fans and supporters.', '2023-06-14 15:36:17', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (6, 20, 'This blog post perfectly captures the way sports can bring people together, fostering a sense of belonging and community.', '2023-04-26 07:17:40', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (44, 9, 'I am constantly amazed by the strategic thinking and mental toughness required in sports.', '2022-02-08 05:56:09', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (27, 4, 'Sports have the ability to break down barriers and bridge divides, promoting inclusivity and equality.', '2022-08-20 08:34:32', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (28, 9, 'This blog post reminds me of the countless hours of joy and excitement that sports have brought into my life.', '2022-12-09 21:03:15', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (36, 14, 'I am grateful for the athletes who use their platform to make a positive impact and inspire change.', '2023-03-29 05:30:08', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (51, 17, 'Sports have a way of teaching us resilience and the importance of bouncing back from setbacks.', '2021-03-12 17:40:36', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (21, 14, 'Gaming has become a wonderful form of entertainment and escapism.', '2023-05-06 10:32:05', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (30, 1, 'I am constantly amazed by the incredible worlds and storytelling in video games.', '2020-11-16 06:05:01', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (30, null, 'This blog post perfectly captures the joy and excitement that gaming brings into our lives.', '2021-08-31 15:44:43', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (19, 14, 'Gaming has a way of immersing us in new adventures and experiences.', '2022-10-17 18:04:07', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (38, 5, 'I couldnt agree more with the points made in this blog post. Gaming is a true art form.', '2022-12-05 00:41:38', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (21, 6, 'I love how gaming can transport us to different worlds and let us be a part of epic stories.', '2021-09-03 15:02:49', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (45, 16, 'The creativity and innovation in the gaming industry are truly mind-blowing.', '2021-10-28 20:06:24', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (54, 18, 'I have discovered so many amazing games through this blog. It is expanded my gaming horizons.', '2023-04-05 13:47:49', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (54, 8, 'Gaming has the power to bring people together and create lasting friendships.', '2023-01-06 23:26:43', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (9, 18, 'I am grateful for the countless hours of fun and excitement that gaming has provided me.', '2020-12-21 09:18:37', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (29, 7, 'The way games challenge us and encourage problem-solving skills is fantastic.', '2021-09-16 07:57:51', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (38, 1, 'This blog post highlights the way gaming can be a form of self-expression and creativity.', '2022-02-02 18:44:43', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (37, 8, 'Gaming has a way of sparking our imagination and taking us on incredible journeys.', '2022-06-20 11:26:42', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (30, 3, 'I appreciate how this blog post explores the positive impact of gaming on mental stimulation and cognitive abilities.', '2022-09-27 16:52:05', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (45, 5, 'Gaming has the power to bring people from different backgrounds together, fostering a sense of community.', '2023-05-23 19:29:17', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 5, 'This blog post reminds me of the nostalgic memories I have of playing games from my childhood.', '2022-10-07 17:41:58', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (38, 11, 'I am grateful for the developers who pour their passion and talent into creating unforgettable gaming experiences.', '2020-10-20 16:28:31', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, 2, 'Gaming has a way of challenging us and pushing us to overcome obstacles.', '2022-03-04 05:06:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (7, 3, 'This blog post perfectly captures the way gaming can provide a much-needed escape from reality.', '2022-01-20 09:46:25', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (45, 2, 'I appreciate the way gaming can transport us to different time periods and cultures, promoting diversity and understanding.', '2022-10-17 09:31:44', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (9, 2, 'This blog post is a testament to the way gaming has evolved and become a mainstream form of entertainment.', '2022-08-03 01:43:37', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (29, 7, 'Gaming has a way of connecting people across the globe, breaking down geographical barriers.', '2022-08-01 03:23:57', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (45, 8, 'I cant imagine a world without gaming. It has become an integral part of our culture.', '2020-12-19 08:35:01', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 19, 'I appreciate how this blog post explores the social aspect of gaming and the communities that form around shared interests.', '2022-09-24 14:00:08', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (21, null, 'Gaming has the power to inspire us and ignite our creativity.', '2022-03-28 09:02:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (37, null, 'This blog post reminds me of the incredible technological advancements in the gaming industry.', '2022-07-02 19:59:55', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (7, 12, 'I am grateful for the memories and experiences I have had playing games with friends and family.', '2021-06-15 02:53:45', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (46, 3, 'Gaming has a way of providing a sense of achievement and accomplishment.', '2021-04-14 14:53:58', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (21, 3, 'This blog post highlights the way gaming can be a source of relaxation and stress relief.', '2020-09-24 17:58:46', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (37, 20, 'I am constantly amazed by the breathtaking visuals and immersive sound design in modern games.', '2021-04-28 01:07:07', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (45, 8, 'Gaming has the ability to tell powerful stories and evoke strong emotions.', '2022-03-02 19:40:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 7, 'This blog post reminds me of the importance of balance and moderation in gaming.', '2022-06-24 05:46:44', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (30, null, 'I am grateful for the diverse range of gaming genres and experiences available to us.', '2022-09-05 13:51:27', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (21, 9, 'Gaming has a way of bringing out our competitive spirit and driving us to improve.', '2021-10-20 02:31:35', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (7, 16, 'This blog post perfectly captures the sense of community and camaraderie that gaming fosters.', '2021-02-22 19:39:31', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (9, 17, 'I appreciate how gaming can be a platform for self-discovery and personal growth.', '2021-01-26 21:20:17', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (19, 15, 'Gaming has the power to introduce us to new cultures and perspectives.', '2023-01-21 14:42:30', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (53, 4, 'This blog post highlights the positive impact of gaming on problem-solving skills and critical thinking.', '2022-12-19 09:08:36', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, 7, 'I am constantly in awe of the talented voice actors, musicians, and artists who contribute to the gaming industry.', '2021-03-11 21:32:40', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 5, 'Gaming has the ability to transport us to different dimensions and let us explore fantastical worlds.', '2020-12-28 08:08:28', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (30, null, 'This blog post reminds me of the friendships I have formed through online gaming communities.', '2021-01-17 23:14:04', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, null, 'I am grateful for the educational aspects of gaming, such as history or science-based games.', '2022-08-23 17:06:06', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (7, 1, 'Gaming has a way of fostering creativity and allowing us to unleash our imagination.', '2023-04-17 12:36:51', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (45, 2, 'This blog post perfectly captures the sense of accomplishment that comes from completing challenging gaming quests.', '2021-07-10 12:43:46', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (9, 16, 'I appreciate how gaming can be a platform for inclusivity and representation.', '2021-01-09 16:14:34', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (29, 9, 'Gaming has the power to inspire us to pursue careers in game development or related fields', '2021-04-28 08:32:27', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (19, 11, 'This blog post highlights the way gaming can provide a sense of belonging and acceptance.', '2022-06-25 20:20:06', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (21, 3, 'I am constantly amazed by the vibrant and passionate gaming community.', '2021-10-28 21:00:55', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (30, 14, 'Gaming has a way of providing us with unforgettable moments and memories.', '2022-08-05 16:26:28', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, 5, 'This blog post reminds me of the power of nostalgia and how gaming can take us back to cherished memories.', '2020-11-19 07:53:52', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (7, 19, 'I am grateful for the way gaming encourages teamwork and cooperation through multiplayer experiences.', '2021-06-17 23:00:02', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (29, 12, 'Gaming has the ability to challenge societal norms and tell thought-provoking stories.', '2021-09-15 05:21:43', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 12, 'This blog post perfectly captures the thrill of discovery and exploration in open-world games.', '2022-12-21 00:35:17', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (9, 10, 'I appreciate how gaming can be a platform for personal expression and creativity.', '2023-01-26 16:08:32', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (19, 19, 'Gaming has the power to provide a sense of achievement and progression.', '2023-04-21 12:54:44', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, 7, 'This blog post highlights the positive impact of gaming on hand-eye coordination and problem-solving abilities.', '2021-03-02 07:59:51', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (54, 17, 'I am constantly in awe of the intricate game design and attention to detail in modern games.', '2022-04-09 09:22:14', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 16, 'Gaming has a way of fostering friendships and connections that transcend geographical boundaries.', '2021-04-16 12:09:52', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, 19, 'This blog post reminds me of the joy and excitement that gaming brings into our lives.', '2022-11-21 20:24:28', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (21, 1, 'I am grateful for the moments of pure joy and exhilaration that gaming has given me.', '2022-11-06 23:42:31', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, 8, 'Gaming has the ability to ignite our imagination and spark our curiosity.', '2023-03-27 15:37:52', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (45, 20, 'This blog post perfectly captures the sense of adventure and exploration in gaming.', '2020-10-14 07:33:22', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 16, 'I appreciate how gaming can be a form of relaxation and a way to unwind after a long day.', '2022-01-20 11:48:57', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 7, 'Gaming has the power to transport us to different time periods and historical events.', '2021-07-21 18:00:30', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (20, 7, 'This blog post highlights the way gaming can be a platform for social interaction and communication.', '2022-12-03 12:40:28', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (46, 15, 'I am constantly amazed by the incredible soundtracks and audio design in games.', '2022-06-25 04:35:56', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (37, null, 'Gaming has a way of teaching us valuable skills such as problem-solving and strategic thinking.', '2023-05-04 18:58:36', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (53, 3, 'This blog post reminds me of the positive impact gaming can have on mental well-being and cognitive abilities.', '2023-02-06 07:24:55', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (30, 20, 'I am grateful for the friendships I have formed through online gaming communities.', '2021-10-08 05:34:20', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (53, null, 'Gaming has the ability to inspire us to think creatively and outside the box.', '2021-01-27 23:42:24', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (8, 8, 'This blog post perfectly captures the sense of adventure and excitement that gaming provides.', '2023-02-16 02:12:53', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (7, 10, 'I appreciate how gaming can be a form of self-care and a way to destress.', '2022-05-15 05:14:33', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (48, 19, 'This blog post provides valuable insights into managing personal finances effectively.', '2022-11-26 12:03:09', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (47, 3, 'I appreciate the practical tips and strategies shared in this post for achieving financial stability.', '2022-12-08 10:42:20', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (48, 20, 'Finance is such an important aspect of our lives, and this blog post sheds light on its significance.', '2022-07-03 14:28:51', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (48, 6, 'I am grateful for the informative content on financial planning and budgeting in this blog post.', '2020-11-26 11:36:30', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (40, 5, 'This post highlights the importance of investing wisely and making informed financial decisions.', '2023-03-20 23:24:42', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (32, 18, 'I couldnt agree more with the points made in this blog post about the benefits of long-term financial planning.', '2023-06-01 00:54:48', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (12, 17, 'The advice and guidance provided in this post are highly valuable for anyone looking to improve their financial situation.', '2021-12-31 08:15:37', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (23, 1, 'I appreciate the emphasis on financial literacy and the resources shared in this blog post.', '2022-03-31 11:18:42', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (10, 15, 'This blog post offers practical steps to achieve financial independence and security.', '2021-04-01 23:16:24', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (12, 9, 'I am constantly amazed by the impact that proper financial management can have on our lives.', '2023-03-28 17:36:10', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (22, 15, 'The insights shared in this post have motivated me to take control of my finances and work towards my financial goals.', '2021-06-08 10:03:10', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (48, null, 'I am grateful for the explanations and examples provided in this blog post, which make complex financial concepts easier to understand.', '2021-03-15 17:53:20', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (39, 18, 'This post highlights the importance of building an emergency fund and being prepared for unexpected expenses.', '2023-02-09 20:36:14', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (10, 5, 'I appreciate the focus on the long-term benefits of saving and investing in this blog post.', '2022-04-21 11:19:07', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (24, 6, 'This blog post serves as a reminder to make informed decisions about money and avoid unnecessary debt.', '2021-09-22 21:32:44', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (47, 6, 'I am grateful for the tips on how to save money and cut expenses shared in this post.', '2023-01-26 14:54:39', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (23, 7, 'The insights into retirement planning and the importance of starting early are invaluable in this blog post.', '2020-09-09 19:11:59', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (11, 13, 'This post emphasizes the value of financial goal-setting and the satisfaction of achieving them.', '2023-05-02 04:49:20', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (10, 8, 'I appreciate the encouragement to seek professional financial advice and the resources provided in this blog post.', '2021-07-25 01:18:43', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (11, 16, 'This blog post highlights the importance of educating ourselves about financial matters and taking control of our financial future.', '2022-02-10 02:38:53', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (56, 10, 'I am grateful for the guidance on how to develop a solid financial strategy outlined in this post.', '2022-04-29 03:21:07', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (32, 12, 'The insights shared in this blog post have inspired me to be more proactive in managing my investments.', '2021-03-24 17:58:52', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (55, 13, 'I appreciate the reminders to review and adjust my financial plan regularly in this post.', '2022-04-20 05:38:12', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (23, 9, 'This post serves as a reminder to prioritize saving for retirement and making the most of retirement accounts.', '2023-03-17 07:12:35', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (48, 18, 'I am constantly amazed by the power of compound interest and the benefits of starting to invest early, as explained in this blog post.', '2022-08-17 03:07:50', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (56, 16, 'The insights into different investment options and their potential returns are highly valuable in this post.', '2022-07-28 12:18:18', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (39, 2, 'I appreciate the tips on how to develop good financial habits and avoid common money pitfalls shared in this blog post.', '2023-02-07 18:34:37', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (22, 14, 'This blog post highlights the importance of diversifying investments and minimizing risks.', '2022-05-04 19:26:10', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (23, 16, 'I am grateful for the reminders to track expenses and create a budget to better manage my finances, as mentioned in this post.', '2021-03-16 13:42:14', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (48, 9, 'This post serves as a reminder to prioritize saving for major life goals, such as buying a house or starting a family.', '2020-10-19 11:21:49', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (23, 6, 'I appreciate the advice on how to handle debt and develop a plan to become debt-free shared in this blog post.', '2023-01-01 04:24:55', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (55, null, 'This blog post provides a clear roadmap for achieving financial freedom and enjoying a stress-free financial life.', '2020-08-17 15:19:42', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (10, 20, 'I am constantly amazed by the positive impact that good financial habits can have on our overall well-being.', '2020-12-20 19:53:12', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (48, 10, 'The insights into effective tax planning and strategies mentioned in this post are highly informative.', '2022-01-17 17:43:53', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (39, 7, 'I appreciate the reminders to stay disciplined and stick to my financial plan, even in challenging times, as discussed in this blog post.', '2022-03-16 21:45:32', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (10, 9, 'This post highlights the importance of setting realistic financial goals and breaking them down into actionable steps.', '2021-07-19 11:49:08', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (56, 17, 'I am grateful for the practical tips on how to save money on everyday expenses shared in this blog post.', '2022-04-29 20:54:30', false);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (39, 1, 'The insights into the psychology of money and the importance of mindset in achieving financial success are eye-opening in this post.', '2020-07-08 00:40:26', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (55, 2, 'I appreciate the encouragement to develop multiple streams of income and explore different avenues for financial growth mentioned in this blog post.', '2021-01-30 20:40:53', true);
insert into comments (post_id, user_id, comment, creation_date, is_confirmed) values (55, 4, 'This blog post serves as a reminder to prioritize investing in ourselves and our skills for long-term financial success.', '2023-05-28 04:26:27', false);